import re

x = """CM_zC1GjQEA
| CMtnud_jQ7e |
| CN323eXhnIZ |
| CN909hfJ5uu |
| CNcAue_hVtu |
| CNG6L_lDcOr |
| CNj2FRtp0q6 |
| CNq_TPthQpK |
| CNwcwiHJTwv |
| CNwGXn1jzBh |
| CO-bdisgRyJ |
| CO-p_fSgz8U |
| CO-X-0uBYIl |
| CO-X1vQhFK0 |
| CO-X32xhl6s |
| CO-X7adhLap |
| CO-YBDvBtxN |
| CO1shQwhRxo |
| CO1U13FhUNg |
| CO1VIDMhoDx |
| CO4w3ivpCuF |
| CO9gybRBNLg |
| CO9qTuipN3a |
| COCFySsjPMD |
| COcMKwihfbD |
| COcNTAMBEuJ |
| COcUBgGj8Cp |
| COeiUyFjqwu |
| COhYbj3hWW- |
| COj3yGGp5zn |
| COJ7bx-BcSx |
| COkkQ0MhO1f |
| CONLv2xDKA0 |
| COpwPdnBNOk |
| COQRyJupxlR |
| COrbBGRBqcD |
| COw6gPdBnio |
| COzwcsSJwxc |
| CP-d6zGh1Kd |
| CP-VHmepcaU |
| CP-Zd9HBdDo |
| CP2FnAmgHJ4 |
| CP2fq_8Dtxl |
| CP2rWUOBOqm |
| CP5y_ZUgqci |
| CP7Y8BeBViE |
| CP8LoGXhThB |
| CP8Qox5jAcr |
| CP9rzaQBDUo |
| CPA9iQtprnT |
| CPAikh2g5ur |
| CPaS67_AM36 |
| CPavjazgFsI |
| CPBCFmbA8eE |
| CPBDOxHgIgZ |
| CPdFYmLALeD |
| CPdSlYsDqW1 |
| CPDZVKUA3Ul |
| CPF0rQjpQ6x |
| CPf4mkuDL8Y |
| CPFELLagVc8 |
| CPFwM2jgriJ |
| CPfwt5YA8ck |
| CPFZQfABf4j |
| CPGNcc6AaeJ |
| CPH0mWeBtb0 |
| CPhfe51jzSu |
| CPhqb9xh_G8 |
| CPIjY5ljT-1 |
| CPilrfej668 |
| CPIrO_7gVGs |
| CPjdNaChH79 |
| CPKfo8ogtN- |
| CPkh_bJJl2R |
| CPkVGLJj64y |
| CPlApYthKMn |
| CPLb3CeAFZi |
| CPlC-7DgtH8 |
| CPlNtUKgopB |
| CPLRL6_DcrS |
| CPnarZDAqWm |
| CPOCvTQAY8X |
| CPPT4OtD6Yk |
| CPQdZrPApxG |
| CPrxORxhOuI |
| CPs43nvAou8 |
| CPS97XRhskm |
| CPsFI4XBS6y |
| CPsmirRDFtY |
| CPSynkmDUeW |
| CPVFFoBAH7b |
| CPxPx3sDSCZ |
| CPXT3HIgDHT |
| CPyDyvxgaGP |
| CPYTm-PATim |
| CPz1_5ngnHp |
| CQA-opigI35 |
| CQAq6PODfLA |
| CQED0_Ah8vx |
| CQFGPIODJul |
| CQG6SAMg3O0 |
| CQGs7b_AbNf |
| CQIgE4kgHoQ |
| CQLSVtvjGV9 |
| CQLZqK3hx6n"""

x = re.sub('\n', '', x)
x = re.sub('[|]', '', x)
x_list = list(x.split('  '))
print(len(x_list))